/*
  Configure antes de publicar:
  const API_URL = "https://SEU-BACKEND.com/api";
*/
const API_URL = "https://corrida-hcgm.onrender.com/api";
const CONFIG={kits:[
{id:"basico",name:"Corrida / Caminhada",price:19.90,medal:false,shirt:false,description:"Somente participação na corrida ou caminhada."},
{id:"medalha",name:"Com Medalha",price:39.90,medal:true,shirt:false,description:"Participação + medalha."},
{id:"completo",name:"Kit Completo",price:59.90,medal:true,shirt:true,description:"Participação + medalha + camiseta unissex."}],
distances:["2,5 km","5 km"],modes:["Corrida","Caminhada"],shirts:["PP","P","M","G","GG","XGG"]};
const state={participants:[],payment:null,timer:null,poll:null};
const money=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function renderKits(){document.getElementById("kitCards").innerHTML=CONFIG.kits.map((k,i)=>`<article class="kit-card ${i===2?"featured":""}"><h3>${k.name}</h3><div class="price">${money(k.price)}</div><p>${k.description}</p><ul><li>2,5 km ou 5 km</li><li>Corrida ou caminhada</li>${k.medal?"<li>Medalha inclusa</li>":""}${k.shirt?"<li>Camiseta unissex</li>":""}</ul><a href="#inscricao" class="btn btn-primary">SELECIONAR</a></article>`).join("")}
function participant(){return{name:"",whatsapp:"",mode:"Corrida",distance:"2,5 km",kitId:"basico",shirt:""}}
function renderParticipants(){const c=document.getElementById("participants");c.innerHTML=state.participants.map((p,i)=>{const k=CONFIG.kits.find(x=>x.id===p.kitId)||CONFIG.kits[0];return `<article class="participant" data-index="${i}"><div class="participant-head"><h3>Participante ${i+1}</h3><span>${money(k.price)}</span></div><div class="fields">
<label>Nome completo<input data-field="name" value="${esc(p.name)}" required></label>
<label>WhatsApp<input data-field="whatsapp" value="${esc(p.whatsapp)}" required></label>
<label>Modalidade<div class="radio-group">${CONFIG.modes.map(m=>`<label class="radio-option"><input data-field="mode" type="radio" name="mode-${i}" value="${m}" ${p.mode===m?"checked":""}> ${m}</label>`).join("")}</div></label>
<label>Distância<select data-field="distance">${CONFIG.distances.map(d=>`<option ${p.distance===d?"selected":""}>${d}</option>`).join("")}</select></label>
<label>Kit / valor<select data-field="kitId">${CONFIG.kits.map(k2=>`<option value="${k2.id}" ${p.kitId===k2.id?"selected":""}>${k2.name} — ${money(k2.price)}</option>`).join("")}</select></label>
<label class="shirt-field" style="${k.shirt?"display:block":"display:none"}">Tamanho da camiseta<select data-field="shirt" ${k.shirt?"required":""}><option value="">Selecione</option>${CONFIG.shirts.map(s=>`<option ${p.shirt===s?"selected":""}>${s}</option>`).join("")}</select></label>
</div></article>`}).join("");
c.querySelectorAll(".participant").forEach(card=>{card.addEventListener("input",changeParticipant);card.addEventListener("change",changeParticipant)});updateSummary()}
function changeParticipant(e){const card=e.currentTarget,i=+card.dataset.index,f=e.target.dataset.field;if(!f)return;if(f==="mode")state.participants[i].mode=e.target.value;else state.participants[i][f]=e.target.value;if(f==="kitId")renderParticipants();else updateSummary()}
function updateSummary(){const total=state.participants.reduce((s,p)=>s+(CONFIG.kits.find(k=>k.id===p.kitId)||CONFIG.kits[0]).price,0);document.getElementById("participantCount").textContent=state.participants.length;document.getElementById("summaryCount").textContent=state.participants.length;document.getElementById("summaryTotal").textContent=money(total);return total}
function qty(d){const n=Math.max(1,Math.min(20,state.participants.length+d));if(n===state.participants.length)return;if(n>state.participants.length)state.participants.push(participant());else state.participants.pop();renderParticipants()}
async function createPayment(e){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;if(!API_URL||API_URL.includes("COLE_AQUI")){document.getElementById("formMessage").textContent="Configure a URL do backend no script.js.";return}if(state.participants.some(p=>p.kitId==="completo"&&!p.shirt)){alert("Selecione o tamanho da camiseta para todos os Kits Completos.");return}
const btn=document.getElementById("submitBtn"),msg=document.getElementById("formMessage");btn.disabled=true;btn.textContent="CRIANDO PIX...";msg.textContent="";
try{const r=await fetch(API_URL+"/registrations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({responsible:{name:document.getElementById("responsibleName").value.trim(),whatsapp:document.getElementById("responsibleWhatsapp").value.trim(),email:document.getElementById("responsibleEmail").value.trim()},participants:state.participants})});const data=await r.json();if(!r.ok||!data.success)throw Error(data.message||"Não foi possível criar a cobrança.");showPayment(data)}catch(err){msg.textContent=err.message}finally{btn.disabled=false;btn.textContent="GERAR PAGAMENTO PIX"}}
function showPayment(data){state.payment=data;document.getElementById("paymentTotal").textContent=money(data.total);document.getElementById("registrationId").textContent=data.registrationId;document.getElementById("pixCode").textContent=data.pixCode;document.getElementById("qrCode").src="data:image/png;base64,"+data.qrCodeBase64;document.getElementById("payment").classList.remove("hidden");document.getElementById("payment").scrollIntoView({behavior:"smooth"});startCountdown(new Date(data.expiresAt).getTime());startPolling()}
function startCountdown(t){clearInterval(state.timer);state.timer=setInterval(()=>{const ms=Math.max(0,t-Date.now()),s=Math.floor(ms/1000);document.getElementById("countdown").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;if(!ms){clearInterval(state.timer);document.getElementById("paymentStatusText").textContent="Esta cobrança expirou.";document.getElementById("newPixBtn").classList.remove("hidden")}},1000)}
function startPolling(){clearInterval(state.poll);state.poll=setInterval(async()=>{if(!state.payment)return;try{const r=await fetch(API_URL+"/registrations/"+encodeURIComponent(state.payment.registrationId)+"/status");const d=await r.json();if(d.status==="PAGO"||d.status==="paid"){clearInterval(state.poll);clearInterval(state.timer);document.getElementById("paymentStatusText").textContent="Pagamento identificado automaticamente.";document.getElementById("paidBox").classList.remove("hidden");document.getElementById("newPixBtn").classList.add("hidden")}}catch(e){}},5000)}
async function newPix(){if(!state.payment)return;document.getElementById("newPixBtn").classList.add("hidden");try{const r=await fetch(API_URL+"/registrations/"+encodeURIComponent(state.payment.registrationId)+"/pix",{method:"POST"});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||"Erro ao gerar novo Pix.");showPayment(d)}catch(e){document.getElementById("paymentMessage").textContent=e.message}}
document.addEventListener("DOMContentLoaded",()=>{renderKits();state.participants=[participant()];renderParticipants();document.getElementById("plusParticipant").onclick=()=>qty(1);document.getElementById("minusParticipant").onclick=()=>qty(-1);document.getElementById("registrationForm").onsubmit=createPayment;document.getElementById("newPixBtn").onclick=newPix;document.getElementById("copyPix").onclick=async()=>{await navigator.clipboard.writeText(document.getElementById("pixCode").textContent);document.getElementById("copyPix").textContent="COPIADO";setTimeout(()=>document.getElementById("copyPix").textContent="COPIAR",1500)}});
